steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/recipe-backend", "."]
    secretEnv:
      - DB_HOST
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - ACCESS_SECRET_KEY
      - REFRESH_SECRET_KEY
      - DEFAULT_PROFILE_PICTURE_URL

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/recipe-backend"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "backend",
        "--image",
        "gcr.io/$PROJECT_ID/recipe-backend",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]
    secretEnv:
      - DB_HOST
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - ACCESS_SECRET_KEY
      - REFRESH_SECRET_KEY
      - DEFAULT_PROFILE_PICTURE_URL

secrets:
- secretEnv:
    DB_HOST: projects/$PROJECT_ID/secrets/DB_HOST/versions/latest
    DB_NAME: projects/$PROJECT_ID/secrets/DB_NAME/versions/latest
    DB_USERNAME: projects/$PROJECT_ID/secrets/DB_USERNAME/versions/latest
    DB_PASSWORD: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
    CLOUDINARY_CLOUD_NAME: projects/$PROJECT_ID/secrets/CLOUDINARY_CLOUD_NAME/versions/latest
    CLOUDINARY_API_KEY: projects/$PROJECT_ID/secrets/CLOUDINARY_API_KEY/versions/latest
    CLOUDINARY_API_SECRET: projects/$PROJECT_ID/secrets/CLOUDINARY_API_SECRET/versions/latest
    ACCESS_SECRET_KEY: projects/$PROJECT_ID/secrets/ACCESS_SECRET_KEY/versions/latest
    REFRESH_SECRET_KEY: projects/$PROJECT_ID/secrets/REFRESH_SECRET_KEY/versions/latest
    DEFAULT_PROFILE_PICTURE_URL: projects/$PROJECT_ID/secrets/DEFAULT_PROFILE_PICTURE_URL/versions/latest

options:
  logging: CLOUD_LOGGING_ONLY
