steps:
  # Copy .env file from Cloud Storage
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", ".env"]

  # 1. Build Docker image for backend with caching
  - name: "gcr.io/cloud-builders/docker"
    args: 
      [
        "build", 
        "--cache-from", 
        "gcr.io/$PROJECT_ID/recipe-backend", 
        "-t", 
        "gcr.io/$PROJECT_ID/recipe-backend:${SHORT_SHA}", 
        "."
      ]

  # 2. Push to Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/recipe-backend:${SHORT_SHA}"]

  # 3. Deploy to Cloud Run with environment variables
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "backend",
        "--image",
        "gcr.io/$PROJECT_ID/recipe-backend:${SHORT_SHA}",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--set-env-vars",
        "PORT=${_PORT},DB_NAME=${_DB_NAME},DB_USERNAME=${_DB_USERNAME},DB_PASSWORD=${_DB_PASSWORD},DB_HOST=${_DB_HOST},CLOUDINARY_CLOUD_NAME=${_CLOUDINARY_CLOUD_NAME},CLOUDINARY_API_KEY=${_CLOUDINARY_API_KEY},CLOUDINARY_API_SECRET=${_CLOUDINARY_API_SECRET},DEFAULT_PROFILE_PICTURE_URL=${_DEFAULT_PROFILE_PICTURE_URL},ACCESS_SECRET_KEY=${_ACCESS_SECRET_KEY},REFRESH_SECRET_KEY=${_REFRESH_SECRET_KEY}"
      ]

# Logs will only be stored in Google Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY
